context:
  version: "11.7.3"

package:
  name: mocha
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/mocha/-/mocha-${{ version }}.tgz
  sha256: ae5b49d554dfe75c43ec8a956384ff47cf3f7b400c582c5e5d77c7cd823d3183

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - mocha --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: simple, flexible, fun javascript test framework for node.js & the browser
  homepage: https://github.com/mochajs/mocha
  repository: https://github.com/mochajs/mocha

extra:
  recipe-maintainers:
    - danielnachun
