context:
  version: "11.7.6"

package:
  name: mocha
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/mocha/-/mocha-${{ version }}.tgz
  sha256: 446cd52e08e21f3f667ef6d500a72b262466c885530ff8e415c6d3a2fc4eacfd

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - mocha --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: simple, flexible, fun javascript test framework for node.js & the browser
  homepage: https://github.com/mochajs/mocha
  repository: https://github.com/mochajs/mocha

extra:
  recipe-maintainers:
    - danielnachun
