context:
  version: "12.0.3"

package:
  name: mocha
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/mocha/-/mocha-${{ version }}.tgz
  sha256: 3a93ba09b4b5f591a947ef5226ca9ae76220b124fe610dbcd5b76eb320512919

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - mocha --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: simple, flexible, fun javascript test framework for node.js & the browser
  homepage: https://github.com/mochajs/mocha
  repository: https://github.com/mochajs/mocha

extra:
  recipe-maintainers:
    - danielnachun
