context:
  version: "11.3.0"

package:
  name: mocha
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/mocha/-/mocha-${{ version }}.tgz
  sha256: 393c0db0895f526e18c26b8faf40ef51142f3e4533293ab8e4a4454e6d7919a0

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - mocha --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: simple, flexible, fun javascript test framework for node.js & the browser
  homepage: https://github.com/mochajs/mocha
  repository: https://github.com/mochajs/mocha

extra:
  recipe-maintainers:
    - danielnachun
