context:
  version: "11.5.0"

package:
  name: mocha
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/mocha/-/mocha-${{ version }}.tgz
  sha256: cfaf5b663b4f85ec904050afcda1cd8cfc50968ff3bcd93a83e4b995e0486b7a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - mocha --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: simple, flexible, fun javascript test framework for node.js & the browser
  homepage: https://github.com/mochajs/mocha
  repository: https://github.com/mochajs/mocha

extra:
  recipe-maintainers:
    - danielnachun
